stages:
  - deploy

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - repo=$(cat $TRIGGER_PAYLOAD | python -c "import sys, json; print(json.load(sys.stdin)['event_data']['repository']['name'])")
    - export repo
    - cat $repo
  #  - kubectl apply -f k8s/simple-go-server.yaml
  #  - job_id="id${CI_JOB_ID}"
  #  - export job_id
  #  - kubectl patch deployment simple-go-server -p '{"spec":{"template":{"metadata":{"labels":{"CI_JOB_ID":"'$CI_JOB_ID'"}}}}}'
