variables:
  #payload: "{"type":"PUSH_ARTIFACT","occur_at":1647545657,"operator":"tbs","event_data":{"resources":[{"digest":"sha256:bc768ff13e3de4c9f2ee43a5635c780845bc95e905f8f896020c29d6c3e34791","tag":"latest","resource_url":"172.16.228.29/demoapp/products:latest"}],"repository":{"date_created":1647540874,"name":"products","namespace":"demoapp","repo_full_name":"demoapp/products","repo_type":"public"}},"id":"9","ref":"master","variables":{}}"
  repo: ""

stages:
  - preprocess
  - deploy

preprocess:
  image: python:latest
  stage: preprocess
  script:
    - python --version
    #- echo $payload | python -mjson.tool
    - echo $TRIGGER_PAYLOAD | python -mjson.tool
  #  - echo '$payload' | python -c "import sys, json; print(json.load(sys.stdin)['event_data']['repository']['name'])"
  #  - echo '$TRIGGER_PAYLOAD' | python -c "import sys, json; print(json.load(sys.stdin)['event_data']['repository']['name'])"

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - cat $repo
  #  - kubectl apply -f k8s/simple-go-server.yaml
  #  - job_id="id${CI_JOB_ID}"
  #  - export job_id
  #  - kubectl patch deployment simple-go-server -p '{"spec":{"template":{"metadata":{"labels":{"CI_JOB_ID":"'$CI_JOB_ID'"}}}}}'
