variables:
  payload: "{type:PUSH_ARTIFACT,occur_at:1647541212,operator:tbs,event_data:{resources:[{digest:sha256:67fcece56ecc7415af65bae342f7c2ea9e08d41aa49a5fab954a708c13876559,tag:b3.20220317.181935,resource_url:172.16.228.29/demoapp/products:b3.20220317.181935}],repository:{date_created:1647540874,name:products,namespace:demoapp,repo_full_name:demoapp/products,repo_type:public}},id:9,ref:master,variables:{}}"
  repo: ""

stages:
  - preprocess
  - deploy

preprocess:
  image: python:latest
  stage: preprocess
  script:
    - $repo=$(echo $payload | python -c "import sys, json; print(json.load(sys.stdin)['event_data']['repository']['name'])")

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - cat $repo
  #  - kubectl apply -f k8s/simple-go-server.yaml
  #  - job_id="id${CI_JOB_ID}"
  #  - export job_id
  #  - kubectl patch deployment simple-go-server -p '{"spec":{"template":{"metadata":{"labels":{"CI_JOB_ID":"'$CI_JOB_ID'"}}}}}'
