stages:
  - deploy

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - cat $CI_TRIGGER_PAYLOAD
  #  - kubectl apply -f k8s/simple-go-server.yaml
  #  - job_id="id${CI_JOB_ID}"
  #  - export job_id
  #  - kubectl patch deployment simple-go-server -p '{"spec":{"template":{"metadata":{"labels":{"CI_JOB_ID":"'$CI_JOB_ID'"}}}}}'
