stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN, building!"

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - kubectl apply -f k8s/simple-go-server.yaml
    - job_id=id_${CI_JOB_ID}
    - export job_id
    - echo $job_id
    - echo "$job_id"
    - kubectl patch deployment simple-go-server -p '{"spec":{"template":{"metadata":{"labels":{"CI_JOB_ID":$job_id}}}}}'
