stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
     - kubectl create ns test123
#    - kubectl apply -f k8s/simple-go-server.yaml -n default
