variables:
  JOB: "A + ${CI_JOB_ID}"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN, building!"

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  only:
    - master
  script:
    - kubectl apply -f k8s/simple-go-server.yaml
    - echo "${CI_JOB_ID}"
    - echo "${CI_JOB_STARTED_AT}"
    - kubectl patch deployment simple-go-server -p '{"spec":{"template":{"metadata":{"labels":{"CI_JOB_ID":'"$JOB"'}}}}}'
