apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  #loadBalancerIP: 10.10.11.203
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: frontend
