apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.228.71
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: orders
