apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.11.201
  ports:
  - targetPort: 8081
    port: 80
    protocol: TCP
  selector:
    app: orders
