apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.228.70
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: products
