apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.71
  ports:
  - targetPort: 8082
    port: 80
    protocol: TCP
  selector:
    app: products
