apiVersion: v1
kind: Service
metadata:
  name: simple-go-server
  labels:
    app: simple-go-server
    tier: cache
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: simple-go-server
---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-server-lb
  labels:
    app: simple-go-server
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: simple-go-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-server
spec:
  selector:
    matchLabels:
      app: simple-go-server
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-go-server
    spec:
      containers:
      - name: simple-go-server
        image: 172.16.228.29/test/simple-go-server:latest
        ports:
        - containerPort: 5000
