apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tanzustore
  annotations:
    external-dns.alpha.kubernetes.io/hostname: store.tanzu.vmlab.fi
    cert-manager.io/issuer: "tanzustore"
spec:
  virtualhost:
    fqdn: store.tanzu.vmlab.fi
    tls:
      secretName: tanzustore-tls
  routes:
  - conditions:
    - prefix: /
    services:
    - name: frontend
      port: 80
  - conditions:
    - prefix: /api/orders
    services:
    - name: orders
      port: 80
  - conditions:
    - prefix: /api/products
    services:
    - name: products
      port: 80
